# permissions for end users to edit custompodrotators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pro
    app.kubernetes.io/managed-by: kustomize
  name: custompodrotator-editor-role
rules:
- apiGroups:
  - apps.tonihacks.com
  resources:
  - custompodrotators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.tonihacks.com
  resources:
  - custompodrotators/status
  verbs:
  - get
