---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.tonihacks.com
  resources:
  - custompodrotators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.tonihacks.com
  resources:
  - custompodrotators/finalizers
  verbs:
  - update
- apiGroups:
  - apps.tonihacks.com
  resources:
  - custompodrotators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
    - apps
  resources:
    - deployments
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - delete
    - create